#
# An example .markdownlint-cli2.yaml file
#

# Disable some built-in rules
config:
  line-length: false

  # Rules that have been dealt with
  blanks-around-fences: true
  blanks-around-headings: true
  blanks-around-lists: true
  no-empty-links: true
  no-multiple-blanks: true
  no-reversed-links: true
  no-trailing-punctuation: true
  single-trailing-newline: true

  # Rules that are temporarily disabled
  fenced-code-language: false
  first-line-heading: false
  ul-indent: false
  ul-style: false
  single-title: false
  no-bare-urls: false
  no-inline-html: false
  no-emphasis-as-heading: false
  commands-show-output: false
  emphasis-style: false
  reference-links-images: false

# # Include a custom rule package
# customRules:
#  - markdownlint-rule-titlecase

# Fix any fixable errors
fix: false

# Define a custom front matter pattern
frontMatter: "<head>[^]*<\/head>"

# # Define glob expressions to use (only valid at root)
# globs:
#  - "!*bout.md"

# # Define glob expressions to ignore
# ignores:
#  - "ignore*.md"

# # Use a plugin to recognize math
# markdownItPlugins:
#  -
#    - "@iktakahiro/markdown-it-katex"

# # Disable inline config comments
# noInlineConfig: true
