path:
  root: ???
  exp_folder: ./results/ # folder to store intermediate signals and final results
  scenes_listeners_file: ${path.root}/clarity_CEC1_data/clarity_data/metadata/scenes_listeners.dev.json
  listeners_file: ${path.root}/clarity_CEC1_data/clarity_data/metadata/listeners.json
  scenes_folder: ${path.root}/clarity_CEC1_data/clarity_data/dev/scenes
  enhanced_signals: ${path.exp_folder}/enhanced_signals

# experimental parameters
num_channels: 3
sample_frequency: 44100
ahr: 20
equiv_0db_spl: 100

GHAHearingAid: # hyperparameters for GHA Hearing Aid, BE CAREFUL if making changes
  sample_frequency: ${sample_frequency}
  ahr: ${ahr}
  audf: null
  cfg_file: prerelease_combination4_smooth
  noise_gate_levels: null
  noise_gate_slope: 0
  cr_level: 0
  max_output_level: 100
  equiv_0db_spl: ${equiv_0db_spl}
  test_nbits: 16

MSBGEar: # hyperparameters for MSBG ear
  src_pos: ff
  sample_frequency: ${sample_frequency}
  equiv_0db_spl: ${equiv_0db_spl}
  ahr: ${ahr}

mbstoi:
  sample_frequency: ${sample_frequency}
  grid_coarseness: 1

# disable hydra loggings
defaults:
  - override hydra/job_logging: disabled

hydra:
  output_subdir: Null
  run:
    dir: .
