path:
  root: ./
  audio_dir: ${path.root}/task2/audio
  metadata_dir: ${path.root}/task2/metadata
  music_dir: ${path.audio_dir}/fma-mtgjamendo
  brird_dir: ${path.audio_dir}/eBrird
  listeners_train_file: ${path.metadata_dir}/listeners.train.json
  listeners_valid_file: ${path.metadata_dir}/listeners.valid.json
  scenes_file: ${path.metadata_dir}/scenes.json
  exp_folder: ./exp # folder to store enhanced signals and final results

nalr:
  nfir: 220
  fs: 44100

compressor:
  threshold: 0.2
  attenuation: 0.1
  attack: 5
  release: 20
  rms_buffer_size: 0.064

soft_clip: True

evaluate:
  set_random_seed: True
  small_test: False
  save_temp_wavs: True

# hydra config
hydra:
  run:
    dir: ${path.exp_folder}